name: CI

on:
  push:
    branches:
      - master
    paths:
      - "**"
      - "!**.md"
      - "!.github/**"
      - ".github/scripts/**"
      - ".github/workflows/build_push.yml"

concurrency:
  group: <span class="math-inline">\{\{ github\.workflow \}\}
cancel\-in\-progress\: true
env\:
BOT\_EMAIL\: "</span>{{ secrets.BOT_EMAIL }}" # Use secrets for sensitive information
  BOT_NAME: "${{ secrets.BOT_NAME }}"

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Find lib changes
        id: modified-libs
        uses: tj-actions/changed-files@v42
        with:
          files: lib/
          files_ignore: lib/**.md
          files_separator: " "
          safe_output: false

      - name: Bump extensions (if needed)
        if: steps.modified-libs.outputs.any_changed == 'true'
        run: |
          python ./.github/scripts/bump-versions.py <span class="math-inline">\{\{ steps\.modified\-libs\.outputs\.all\_changed\_files \}\}
git config \-\-global user\.email "</span>{{ secrets.BOT_EMAIL }}"
          git config --global user.name "${{ secrets.BOT_NAME }}"
          git commit -m "Bumped versions"
          git push

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

  build_individual:
    name: Build individual modules
    needs: prepare
    runs-on: ubuntu-latest
    strategy: # Build matrix for different architectures (optional but recommended)
      matrix:
        arch: [x86_64, arm64] # Add arm64 if needed
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools, build-tools;34.0.0 # Specify necessary packages

      - name: Set up aapt2 (ARM)
        if: matrix.arch == 'arm64' # Use matrix instead of runner.arch
        run: |
          wget https://codeberg.org/hollow/android-sdk-tools/releases/download/v34.0.3/android-sdk-tools-static-arm.zip
          unzip android-sdk-tools-static-arm.zip
          echo "ARM_AAPT=-Pandroid.aapt2FromMavenOverride=$GITHUB_WORKSPACE/build-tools/aapt2" >> <span class="math-inline">GITHUB\_ENV
\- name\: Set up Gradle
uses\: gradle/actions/setup\-gradle@v3
\- name\: Prepare signing key
run\: \|
echo "</span>{{ secrets.SIGNING_KEY }}" | base64 -d > signingkey.jks

      - name: Build extensions
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew $ARM_AAPT -p src assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v3 # Use official action
        if: github.repository == 'hollow/aniyomi-extensions-fr'
        with:
          name: individual-apks
          path: "**/*.apk"
          retention-days: 1

      - name: Clean up CI files
        run: rm signingkey.jks

  publish_repo:
    name: Publish repo
    needs: build_individual
    if: github.repository == 'hollow/aniyomi-extensions-fr'
    runs-on: ubuntu-latest
    steps:
      - name: Setup rsync
        run: |
          sudo apt-get update && sudo apt-get install rsync -y

      - name: Download APK artifacts
        uses: actions/download-artifact@v3 # Use official action
        with:
          name: individual-apks
          path: ~/apk-artifacts

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools, build-tools;34.0.0 # Specify necessary packages

      - name: Set up build-tools (ARM)
        if: runner.arch == 'arm64'
        run: |
          wget https://codeberg.org/hollow/android-sdk-tools/releases/download/v34.0.3/android-sdk-tools-static-arm.zip
          mkdir -p $HOME/.android/sdk/build-tools/
          unzip android-sdk-tools-static-arm.zip -d $HOME/.android/sdk/build-tools/
          mv $HOME/.android/sdk/build-tools/build-tools $HOME/.android/sdk/build-tools/34.0.0
          echo 'ANDROID_DATA=.' >> <span class="math-inline">GITHUB\_ENV
\- name\: Checkout master
uses\: actions/checkout@v3
with\:
ref\: master
path\: master
\- name\: Create repo artifacts
run\: \|
cd master
python \./\.github/scripts/move\-apks\.py
INSPECTOR\_LINK\="</span>(curl -s "https://api.github.com/repos/aniyomiorg/aniyomi-extensions-inspector/releases/latest" | jq -r '.assets[0].browser_download_url')"
          curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
          java -jar ./Inspector.jar "repo/apk" "output.json"
